language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go get github.com/Masterminds/glide
  - glide install

script:
  - make test

env:
  global:
    - GO15VENDOREXPERIMENT="1"
