language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - make test

after_success:
  - make coveralls

env:
  global:
    - GO15VENDOREXPERIMENT="1"
