language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go get github.com/Masterminds/glide

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - GO15VENDOREXPERIMENT="1"
